# Generated by Django 3.2.10 on 2021-12-22 18:24

from django.conf import settings
from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion
import uuid

appLabel = 'candidate'

def loadUserFixtures(apps, schema_editor):
	call_command('loaddata', 'userrole', app_label=appLabel)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=30)),
                ('roleCode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profileId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('userRole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidate.userrole')),
            ],
        ),
        migrations.RunPython(loadUserFixtures),
    ]
