# Generated by Django 4.0 on 2022-01-10 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profileId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('employee', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
                ('userRole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidate.userrole')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jobId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('technology', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('appliedNumber', models.IntegerField(default=0)),
                ('isDeleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidate.candidate')),
                ('jobPost', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.jobpost')),
            ],
        ),
    ]
